name: Token Check

on:
  workflow_dispatch:

jobs:
  npm-token-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Verify NPM Token
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Verifying NPM token..."
          npm whoami
          echo "Success! Token is valid and authenticated."
